# Fundo e fonte
foreground            #F0F0F0
background            #141414
background_opacity    0.9

# Seleção
selection_foreground  #141414
selection_background  #F0F0F0

# Links/URLs
url_color             #CCCCCC

# Cursor
cursor                #F0F0F0
cursor_text_color     #141414

# Cores normais 
color0  #141414
color1  #FF6666
color2  #66FF66
color3  #FFFF66
color4  #6699FF
color5  #FF66FF
color6  #66FFFF
color7  #F0F0F0

# Cores brilhantes
color8  #4D4D4D
color9  #FF7777
color10 #77FF77
color11 #FFFF77
color12 #77AAFF
color13 #FF77FF
color14 #77FFFF
color15 #FFFFFF

# Tabs
active_tab_foreground    #F0F0F0
active_tab_background    #2A2A2A
inactive_tab_foreground  #AAAAAA
inactive_tab_background  #1A1A1A

# Marcas
mark1_foreground          #141414
mark1_background          #FFFF77
mark2_foreground          #141414
mark2_background          #77AAFF
mark3_foreground          #141414
mark3_background          #77FF77