# Dark Minimal :D

# Fundo e fonte
foreground            #E0E0E0
background            #121212   
background_opacity    0.8

# Seleção
selection_foreground  #121212   
selection_background  #E0E0E0   

# Links/URLs
url_color             #AAAAAA   

# Cursor
cursor                #E0E0E0  
cursor_text_color     #121212   

# Cores normais 
color0  #121212  
color1  #BB4444   
color2  #44BB44   
color3  #BBBB44   
color4  #4488BB   
color5  #BB44BB   
color6  #44BBBB   
color7  #E0E0E0   

# Cores brilhantes
color8  #333333
color9  #BB4444
color10 #44BB44
color11 #BBBB44
color12 #4488BB
color13 #BB44BB
color14 #44BBBB
color15 #E0E0E0

# Tabs
active_tab_foreground    #E0E0E0
active_tab_background    #1C1C1C
inactive_tab_foreground  #555555
inactive_tab_background  #121212

# Marcas
mark1_foreground          #121212
mark1_background          #BBBB44
mark2_foreground          #121212
mark2_background          #4488BB
mark3_foreground          #121212
mark3_background          #44BB44