$LOCKSCREEN = hyde-shell lockscreen

general {
    lock_cmd = $LOCKSCREEN
    before_sleep_cmd = loginctl lock-session
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

listener {
    timeout = 20000
    on-timeout = brightnessctl s 1%
    on-resume = brightnessctl -r
}

listener {
    timeout = 500
    on-timeout = loginctl lock-session
}

listener {
    timeout = 1000
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 3000
    on-timeout = systemctl suspend
}

# Custom listeners (não funcional atualmente)
# source = ./hypridle/*