# ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      █████╗ ███╗   ██╗██████╗ 
# ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔══██╗████╗  ██║██╔══██╗
# ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ███████║██╔██╗ ██║██║  ██║
# ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██╔══██║██║╚██╗██║██║  ██║
# ██║  ██║   ██║   ██║     ██║  ██║███████╗██║  ██║██║ ╚████║██████╔╝
# ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝ 
# -------------------------------------------------------------------

################
### MONITORS ###
################
source = ~/.config/hypr/modules/monitors.conf

###################
### MY PROGRAMS ###
###################
source = ~/.config/hypr/modules/programs.conf

#################
### AUTOSTART ###
#################
source = ~/.config/hypr/modules/autostart.conf


#############################
### ENVIRONMENT VARIABLES ###
#############################
source = ~/.config/hypr/modules/environment.conf


#####################
### LOOK AND FEEL ###
#####################
source = ~/.config/hypr/modules/appearance.conf
source = ~/.config/hypr/modules/animation.conf
source = ~/.config/hypr/modules/layout.conf
source = ~/.config/hypr/modules/misc.conf

#############
### INPUT ###
#############
source = ~/.config/hypr/modules/input.conf


###################
### KEYBINDINGS ###
###################
source = ~/.config/hypr/modules/keybinding.conf


####################
### WINDOWS RULE ###
####################
source = ~/.config/hypr/modules/windowrule.conf


#######################
### WORKSPACES RULE ###
#######################
source = ~/.config/hypr/modules/workspaces.conf

##################
### ANIMATIONS ###
##################
source = ~/.config/hypr/modules/animation.conf